 @@ script infofile_;_ZIP::ssf30.xml_;_
 @@ script infofile_;_ZIP::ssf36.xml_;_
'Browser("name:=Bedroom Design: Bedroom Interior Design Services For Home - Asian Paints").Page("title:=Bedroom Design: Bedroom Interior Design Services For Home - Asian Paints").WebElement("xpath:=//DIV\[1\]/DIV\[1\]/DIV\[1\]/HEADER\[1\]/DIV\[2\]/DIV\[2\]/DIV\[1\]").Click @@ script infofile_;_ZIP::ssf37.xml_;_
'Browser("name:=Bedroom Design: Bedroom Interior Design Services For Home - Asian Paints").Page("title:=Bedroom Design: Bedroom Interior Design Services For Home - Asian Paints").WebEdit("xpath:=//*[@id=loginMobile]").Set "6384608096" @@ script infofile_;_ZIP::ssf38.xml_;_
'Browser("name:=Bedroom Design: Bedroom Interior Design Services For Home - Asian Paints").Page("title:=Bedroom Design: Bedroom Interior Design Services For Home - Asian Paints").WebButton("xpath:=//*[@id=validate-otp]/div[3]/button").Click @@ script infofile_;_ZIP::ssf39.xml_;_
Browser("name:=Bedroom Design: Bedroom Interior Design Services For Home - Asian Paints").Page("title:=Bedroom Design: Bedroom Interior Design Services For Home - Asian Paints").WebElement("class:=spriteIcon-Firstfold profileIcon-active").Click @@ script infofile_;_ZIP::ssf42.xml_;_
Browser("name:=Bedroom Design: Bedroom Interior Design Services For Home - Asian Paints").Page("title:=Bedroom Design: Bedroom Interior Design Services For Home - Asian Paints").WebEdit("xpath:=//*[@id=loginMobile]").Set "6384608096" @@ script infofile_;_ZIP::ssf43.xml_;_
Browser("name:=Bedroom Design: Bedroom Interior Design Services For Home - Asian Paints,").Page("title:=Bedroom Design: Bedroom Interior Design Services For Home - Asian Paints").WebButton("xpath:=//*[@id=validate-otp]/div[3]/button").Click @@ script infofile_;_ZIP::ssf44.xml_;_
'Browser("name:=Bedroom Design: Bedroom Interior Design Services For Home - Asian Paints").Page("title:=Bedroom Design: Bedroom Interior Design Services For Home - Asian Paints").WebEdit("LOGIN_OTP").Set "49828" @@ script infofile_;_ZIP::ssf45.xml_;_
'Browser("name:=Bedroom Design: Bedroom Interior Design Services For Home - Asian Paints").Page("title:=Bedroom Design: Bedroom Interior Design Services For Home - Asian Paints").WebButton("SUBMIT_2").Click @@ script infofile_;_ZIP::ssf46.xml_;_
'Browser("name:=Bedroom Design: Bedroom Interior Design Services For Home - Asian Paints,").Page("title:=Bedroom Design: Bedroom Interior Design Services For Home - Asian Paints,").WebEdit("LOGIN_OTP").Set "95118" @@ script infofile_;_ZIP::ssf40.xml_;_
'Browser("name:=Bedroom Design: Bedroom Interior Design Services For Home - Asian Paints,").Page("title:=Bedroom Design: Bedroom Interior Design Services For Home - Asian Paints,").WebButton("SUBMIT_2").Click @@ script infofile_;_ZIP::ssf41.xml_;_
